#!/bin/bash

path="/home/jona/Code/analyze-frontend"
session="iaf"

# Check if the session exists, discarding output
# We can check $? for the exit status (zero for success, non-zero for failure)
tmux has-session -t $session 2>/dev/null

if [ $? != 0 ]
then
    tmux new-session -d -s $session -c $path

    window=1
    tmux rename-window -t $session:$window 'neovim'
    tmux send-keys -t $session:$window 'nvim .' C-m

    window=2
    tmux new-window -t $session:$window -c $path -n 'git'

    window=3
    tmux new-window -t $session:$window -c $path -n 'docker'
    tmux send-keys -t $session:$window 'docker compose up -d' C-m 'docker compose run web npm install' C-m

    cd $path && neovide .
fi

tmux attach-session -t $session:1
