import = ["/home/jona/.config/alacritty/alacritty-theme/themes/breeze.toml"]

[font]
size = 13

[font.bold]
family = "Inconsolata Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Inconsolata Nerd Font"
style = "BoldItalic"

[font.italic]
family = "Inconsolata Nerd Font"
style = "Italic"

[font.normal]
family = "Inconsolata Nerd Font"
style = "Regular"

[font.offset]
x = 2
y = 2

[window]
dynamic_padding = false

[window.padding]
x = 1
y = 1
